export default {
  PRODUCT_REQUEST_SUCCESS: 'PRODUCT_REQUEST_SUCCESS',
  REQUEST_RECIEVED: 'REQUEST_RECIEVED',
  REQUESTS_DISMISSED: 'REQUESTS_DISMISSED',
  REQUESTS_DISMISSED_SUCCESS: 'REQUESTS_DISMISSED_SUCCESS',
  REQUEST_DISMISSED: 'REQUEST_DISMISSED',
  REQUESTS_LOADED: 'REQUESTS_LOADED',
  HISTORY_CLEARED: 'HISTORY_CLEARED',
};
