export default {
  CONNECTING: 'CONNECTING',
  SIGNALR_CONNECT: 'SIGNALR_CONNECT',
  CONNECTION_SUCCEEDED: 'CONNECTION_SUCCEEDED',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  CONNECTION_CLOSED: 'CONNECTION_CLOSED',
  DISCONNECTED: 'DISCONNECTED',
};
