export default {
  SIGNALR: 'SIGNALR',
  SIGNALR_ERROR: 'SIGNALR_ERROR',
  SIGNALR_SUCCESS: 'SIGNALR_SUCCESS',
  SIGNALR_CONNECT: 'SIGNALR_CONNECT',
  SIGNALR_CONNECTED: 'SIGNALR_CONNECTED',
  SIGNALR_CONNECTION_CLOSED: 'SIGNALR_CONNECTION_CLOSED',
  SIGNALR_DISCONNECT: 'SIGNALR_DISCONNECT',
};
