export default {
  API: 'API',
  API_AUTHENTICATED: 'API_AUTHENTICATED',
  API_AUTHENTICATION_ERROR: 'API_AUTHENTICATION_ERROR',
  API_ERROR: 'API_ERROR',
  START_NETWORK: 'START_NETWORK',
  END_NETWORK: 'END_NETWORK',
};
