export default {
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
};
