export default {
  AUTHENTICATING: 'AUTHENTICATING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  TOKEN_RENEW_SUCCESS: 'TOKEN_RENEW_SUCCESS',
  TOKEN_RENEW_FAILED: 'TOKEN_RENEW_FAILED',
};
